var Blueprint = {
    ButtonFactory: function() {},
    SpinnerFactory: function() {},
    EditableTextFactory: function() {},
    Collapse: function() {},
    TabsFactory: function() {},
    TabListFactory: function() {},
    TabFactory: function() {},
    TabPanelFactory: function() {},
    Alert: function() {},
    Breadcrumb: function() {},
    DialogFactory: function() {},
    OverlayFactory: function() {},
    InputGroupFactory: function() {},
    TagFactory: function() {},
    SliderFactory: function() {},
    SwitchFactory: function() {},
    CollapsibleLIstFactory: function() {},
    MenuItemFactory: function() {},
    MenuDividerFactory: function() {},
    MenuFactory: function() {},
    CheckboxFactory: function() {},
    RadioFactory: function() {},
    RadioGroup: function() {},
    NonIdealStateFactory: function() {},
    PopoverFactory: function() {},
    TooltipFactory: function() {},
    ProgressBarFactory: function() {},
    TreeFactory: function() {},
    Toaster: function() {},
    Intent: {},
    ContextMenu: function() {}
}
